spring.application.name=Server


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
#
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
server.port=${SERVER_PORT:8082}
server.servlet.context-path=${CONTEXT_PATH}
#
jwt.secret.key=${JWT_SECRET}
jwt.exp.time=${JWT_EXP_TIME}
#
cors.allowed-origins=${CORS_ALLOW_URL}

logging.level.org.springframework.security=warn
